name: Gradle-CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Gradle Docker image
        run: |
          curl -H "Authorization: token OAUTH-TOKEN" https://api.github.com/user
          docker build . --tag ghcr.io/faisikhan/gradle:$GITHUB_WORKFLOW-$GITHUB_RUN_NUMBER

      - name: Push the Gradle Docker image
        run: |
          docker push ghcr.io/faisikhan/gradle:$GITHUB_WORKFLOW-$GITHUB_RUN_NUMBER
