# name: Gradle CI
# on:
#   push:
#     branches: [ master ]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         java-version: [11]
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK ${{ matrix.java-version }}
#       uses: actions/setup-java@v2
#       with:
#         java-version: ${{ matrix.java-version }}
#         distribution: 'adopt'
#         cache: gradle
#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
#     - name: Build with Gradle
#       run: ./gradlew build

name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
          
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Build the Docker image
        run: |
            docker build . --tag frehman/pipe1:gradle
            
      - name: Logging into the Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          
      - name: Pushing the Image to Docker Hub
        run: |
            docker push frehman/pipe1:gradle
